### ISSUE TITLE
webpack-cli as a production dependency

### ISSUE THREAD

**Issue by lewisf** [EasyPost/easypost-node#106]
Wondering why webpack-cli is a production dependency? If it isn't necessary can it be moved to a dev dependency? It's causing warnings in NPM install because it has a peer dependency on webpack.

```
"@easypost/api > webpack-cli@3.1.0" has unmet peer dependency "webpack@^4.x.x".
```

**Comment by ajacksified** [comment]
Looks like a mistake - updated in latest, `3.6.2`.
