### ISSUE TITLE
Creating child user accounts fails with PARAMETER.REQUIRED

### ISSUE THREAD

**Issue by mikejohanson** [EasyPost/easypost-node#108]
I'm trying to create a child user with the following code pulled from [here]:(https://www.easypost.com/docs/api/node.html#child-users) 

```
const Easypost = require('@easypost/api');
const api = new Easypost('<YOUR_PRODUCTION_API_KEY>');

const user = new api.User({
  name: 'Child Account Name',
})

user.save().then(u => console.log(u.id));
```

However I'm getting the following error: 
```
RequestError {
  error: 
   { error: 
      { code: 'PARAMETER.REQUIRED',
        message: 'Missing required parameter: user',
        errors: [] } },
  name: 'RequestError',
  status: undefined }
```

But i'm not sure what exactly is missing given I am performing the save on the user object itself? Using Postman I was able to make the call just fine, just seems to be an issue with this sdk.

**Comment by ajacksified** [comment]
Should be fixed in 3.6.4. Thanks for the report!
