### ISSUE TITLE
src/resources/report.js doesn't jive with public documentation

### ISSUE THREAD

**Issue by LoganSimonsen** [EasyPost/easypost-node#113]
Here is our public example for generating reports through the API: https://www.easypost.com/docs/api/node#retrieve-a-list-of-a-reports

api.PaymentLogReport doesn't work anymore, related to change in March? What is the new method for generating a payment/refund/shipment/tracker log report?

**Comment by LoganSimonsen** [comment]
sorry, this was solved previously and I forgot, public docs still need to be updated though. submitted internal ticket for that.

`const report = new api.Report({
  type: 'shipment',
  start_date: '2016-10-01',
  end_date: '2016-10-31'
});
report.save().then(console.log);
`

**Comment by k-funk** [comment]
Docs updated for `api.Report.all()` and `api.Report.retrieve`: https://www.easypost.com/docs/api/node#retrieve-a-list-of-a-reports
