### ISSUE TITLE
shipment.convertLabelFormat('PDF') produces label of wrong size

### ISSUE THREAD

**Issue by tobias7an** [EasyPost/easypost-node#114]
4x6" PNG labels are resized to 11.5x8" when converted to PDFs using label conversion API. 
No documentation was found for how to specify output label dimensions.

Sample of problem:
https://easypost-files.s3-us-west-2.amazonaws.com/files/postage_label/20181219/9888a75052924d729e0bb16239fce015.png
is converted to:
https://easypost-files.s3-us-west-2.amazonaws.com/files/postage_label/20181219/7b6d4c88b13c48e983fb1faec1d119ef.pdf

Additionally, suggested workaround of specifying PDF format and 4x6 size in initial options unworkable as some labels are still being returned as 8.5x11 PDFs, and other labels return error SHIPMENT.POSTAGE.FORMAT_UNAVAILABLE.

**Comment by mwaldt** [comment]
Hi,

Please write into support@easypost.com for inquiries like this for quickest results. If you can provide the shipment id for this as well that would save an exchange. 

Since this is not an issue with the node client library specifically I am going to close this issue.
