### ISSUE TITLE
Buy shipment : only able to buy shipment with USPS not with Fedex or any other carrier

### ISSUE THREAD

**Issue by sehgal-kanika** [EasyPost/easypost-node#118]
If i pass carrier as USPS it will give me the proper response with selected shipment , but if i m passing the FedEx it causing an error : 
error:Status undefined returned from API request
to shipments/shp_a080bf254f444f328fb4c33a82fa5ce1/buy

**Comment by sehgal-kanika** [comment]
AS i m using the code : 

const lowestRate = ship.lowestRate(buyCarrier,buyService);
api.Shipment.retrieve('shp_...').then(s => {
  s.buy(lowestRate,0).then(console.log);
});

**Comment by sehgal-kanika** [comment]
If print lowest Rate with  ship.lowestRate(buyCarrier,buyService)

response:

{ id: 'rate_cde5af3722084197b1a05a0646906af4',
  object: 'Rate',
  created_at: '2019-03-22T08:26:15Z',
  updated_at: '2019-03-22T08:26:15Z',
  mode: 'test',
  service: 'SMART_POST',
  carrier: 'FedExSmartPost',
  rate: '8.34',
  currency: 'USD',
  retail_rate: null,
  retail_currency: null,
  list_rate: '8.81',
  list_currency: 'USD',
  delivery_days: 7,
  delivery_date: null,
  delivery_date_guaranteed: false,
  est_delivery_days: 7,
  shipment_id: 'shp_4abbf01ebc7e45d28fb96edcf1196744',
  carrier_account_id: 'ca_e6ae9d31e66f4a499371f922b5cf0b86' }

**Comment by sehgal-kanika** [comment]
Issue was due to the wrong street address in FedEx and they are strict, USPS will allow to buy the shipment but FedEx and other carrier verifying the shipment before buying it.

**Comment by sehgal-kanika** [comment]
as issue resolve closing the issue

**Comment by mwaldt** [comment]
Hi,

For issues like this please contact support@easypost.com for more immediate assistance. Also on a shipment object there is a messages array that will return carrier specific error messages that will detail why they failed to rate. You can read more about our shipment object in our docs as well.
https://www.easypost.com/docs/api#shipments

Cheers,

**Comment by sehgal-kanika** [comment]
Thanks @mwaldt  but node api is not returning proper error, i got to know about my issue with curl hit as its giving proper error message

**Comment by MmtBkn** [comment]
In my case, I didn't realize that weight was required for the parcel, so It was returning this message. If you get this message you are probably missing some required field.
