### ISSUE TITLE
Find saved Shipment by ID

### ISSUE THREAD

**Issue by andrepadez** [EasyPost/easypost-node#123]
looking for a way to NOT having to cache the shipment Object between saving -> get rates -> waiting for user to select rate -> Buy label, `await api.Shipment({ id: <shipment_id>})`.

Is it possible already? How?
if not, would you consider implementing something like this?

Thanks in advance

**Comment by k-funk** [comment]
I'm guessing that you are building some kind of application where your "user" is someone else with a user-interface where they are manually selecting rates.

With that assumption, it really depends on your application.

You could, for example, in HTML have an `<input type="hidden" name="shipment_id" value="shp_1234" />`. Shipments have an `id` field that you can later fetch from EasyPost: https://www.easypost.com/docs/api/node#shipments-retrieve-codesample 

You can apply the same principle for the `rate_123` id that they select when you want to `shipment.buy(rate_id, insurance_amount)`

**Comment by andrepadez** [comment]
Thank you, this is exactly what i was looking for
