### ISSUE TITLE
Retrieval ID for User is not actually optional

### ISSUE THREAD

**Issue by cwidafor** [EasyPost/easypost-node#124]
`(node:16825) UnhandledPromiseRejectionWarning: RequestError: Status undefined returned from API request to users/undefined`

This is what I was getting passed back when trying to attempt:

`EPApi.User.retrieve()`

The docs say the user ID is optional, and it definitely should be. I can see the source code that it is actually always trying to pump through an ID variable, causing the strange "undefined" issue.

Working on a PR

**Comment by cwidafor** [comment]
PR:

#125

**Comment by k-funk** [comment]
@cwidafor thanks for reporting this issue. We'll get a fix out in the next day or two.
