### ISSUE TITLE
How to proxy

### ISSUE THREAD

**Issue by andwilr** [EasyPost/easypost-node#131]
This is less of an issue and more of a general inquiry.

I understand the following from the docs and [this comment](https://github.com/EasyPost/easypost-node/issues/42#issuecomment-273937093):
> we don't allow CORS on our APIs. You will need to build an API proxy which holds the API keys, and make your requests through that proxy.

I've tried building a proxy in Node a few different ways, but it's not working and I can't tell if I'm on the right track or way off.

### Working (no proxy)

I have a test file `index.js` that I run with `node index.js`:
```js
require('dotenv').config();
const Easypost = require('@easypost/api');
const api = new Easypost(process.env.EASYPOST_API_KEY);

// ... do stuff with the api
```
everything works as expected; I get json responses from Easypost etc.

### Not working (my proxy attempt)

I have another test file `server.js` I run with `node server.js`:
```js
require('dotenv').config();
const baseUrl = 'https://api.easypost.com/v2/';
const apiKey = process.env.EASYPOST_API_KEY;
const http = require('http');
const httpProxy = require('http-proxy');

const proxy = new httpProxy.createProxyServer({
    target: baseUrl,
    auth: apiKey,
});

const proxyServer = http.createServer((req, res) => {
    proxy.web(req, res);
});

proxyServer.on('upgrade', (req, socket, head) => {
    proxy.ws(req, socket, head);
});

proxyServer.listen(3000);
```

Once that is running, if I change the api instance in `index.js` to this:
```js
require('dotenv').config();
const Easypost = require('@easypost/api');
const api = new Easypost(process.env.EASYPOST_API_KEY, {
    baseUrl: 'http://localhost:3000/',
    useProxy: true,
});

// ... do stuff with the api
```
running `node index.js` with these changes, the server crashes with this message:
>Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.easypost.com, DNS:easypost.com
    at Object.checkServerIdentity (tls.js:288:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1485:27)
    at TLSSocket.emit (events.js:321:20)
    at TLSSocket._finishInit (_tls_wrap.js:918:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:688:12) {
  reason: "Host: localhost. is not in the cert's altnames: DNS:*.easypost.com, DNS:easypost.com",
... the rest is suppressed

while `index.js` gives this error:
>Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:455:23)
    at Socket.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  response: undefined
}

Any insight, guidance, or working examples of an API proxy for Easypost would be super helpful. I realize I don't need a proxy if using the API in node, but I plan to transition my requests into a client side app once I have the proxying figured out.

**Comment by JHuppi** [comment]
I'm working on an Electron app and would also like to now how to setup a proxy server.

**Comment by rrgrs** [comment]
In your proxy config try setting `changeOrigin` to true:

```
const proxy = new httpProxy.createProxyServer({
  target: baseUrl,
  auth: apiKey,
  changeOrigin: true,
});
```

**Comment by chasedougherty4628** [comment]
Nuxt has a quick way to set up a proxy server.
https://nuxtjs.org/faq/http-proxy/

**Comment by eschutho** [comment]
Looks like there are a few answers to the question, so I'm closing the issue, but let us know if you still have any questions.
