### ISSUE TITLE
How to Create a Shipment with Multiple Parcels

### ISSUE THREAD

**Issue by haseebsaif** [EasyPost/easypost-node#134]
Hello,

I am trying to get the rate of a Shipment with Multiple Parcels for DHL Express, but unable to do so. 

If I pass a single parcel it returns me Price and all the other info but I have multiple Parcels to pass in a single shipment.

How to achieve that?

**Single Parcel: WORK FINE**
```
const parcel = new api.Parcel({
  length: 20.2,
  width: 10.9,
  height: 5,
  weight: 65.9
});

const shp1 = new api.Shipment({
    to_address: 'adr_...',
    from_address: 'adr_...',
    parcel: parcel
});
```
**For Two Parcels: How to achieve that?**
```
??

**Comment by Justintime50** [comment]
Hey @haseebsaif - this is a question better suited for our support team as it is how to implement the API and not a client library issue. Please reach out to support@easypost.com and we'll be able to assist you better there. As such, this issue may be closed. @jontsai
