### ISSUE TITLE
api.Tracker.all with tracking_code parameter does not return only that tracking_code 

### ISSUE THREAD

**Issue by ctogden** [EasyPost/easypost-node#140]
The code below returns multiple trackers (I think perhaps all the trackers I've created but I haven't confirmed):
```
    api.Tracker.all({
      tracker_code: <tracking_code>
    })
```

According to the EasyPost docs, the expected behavior is "Only returns Trackers with the given tracking_code. Useful for retrieving an individual Tracker by tracking_code rather than by ID".

I'm using 3.8.1, the latest release available on npm.

**Comment by Justintime50** [comment]
@ctogden this works as intended as is not a problem with this particular client library; for instance, I just used this and it only returned a single tracker for me. Discarding the `tracking_code` parameter returned the entire list. If you are having the entire list returned, there must be something else wrong in your code.

```javascript
trackers = api.Tracker.all({
    tracking_code: "123456789"
}).then(console.log);
```

If ever you run into issues you'd like EasyPost support on, feel free to email support@easypost.com as we can assist you best there. As such, this issue may be closed. @att14  @jontsai

**Comment by ctogden** [comment]
Ah, I had written tracker_code, not tracking_code. Thanks for the response.
