### ISSUE TITLE
Access to XMLHttpRequest has been blocked by CORS policy

### ISSUE THREAD

**Issue by r-gareva** [EasyPost/easypost-node#152]
Hello, I'm testing EasyPost with testing API key and I keep getting this error. Have no idea how to fix it. I will gladly appreciate if anyone can help me with this. Also tried in Postman to create a test shipment but it doesn't let me create it.

Access to XMLHttpRequest at 'https://api.easypost.com/v2/shipments' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

This is what I have so far:

  const toAddress = new api.Address({
  name: 'Dr. Steve Brule',
  street1: '179 N Harbor Dr',
  city: 'Redondo Beach',
  state: 'CA',
  zip: '90277',
  country: 'US',
  phone: '310-808-5243'
});

const fromAddress = new api.Address({
  name: 'EasyPost',
  street1: '118 2nd Street',
  street2: '4th Floor',
  city: 'San Francisco',
  state: 'CA',
  zip: '94105',
  phone: '415-123-4567'
});

const parcel = new api.Parcel({
  length: 20.2,
  width: 10.9,
  height: 5,
  weight: 65.9
});

const shipment = new api.Shipment({
  to_address: toAddress,
  from_address: fromAddress,
  parcel: parcel,
});

shipment.save().then(console.log);

**Comment by Roguelazer** [comment]
We don't allow Cross-Origin requests because we _strongly recommend against_ using our client libraries from client-side applications. In order to do so, you would have to expose your API keys to your clients, which would allow any of them to trivially abuse your EasyPost account.
