### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by evliu** [EasyPost/easypost-node#16]
Did you guys plan to have an API doc for this, since it's not on the easypost website? Hopefully it'd be easier to implement than going through the source code. Thx

**Comment by gaboesquivel** [comment]
:+1:

**Comment by mugli** [comment]
Still no update? :(

**Comment by vubui** [comment]
This has been forever. 

"No up-to-date doc" in Readme would be nice.

**Comment by ajacksified** [comment]
Hey there,

We're working on docs - we haven't historically had many resources on the node sdk, but I'm here to help. I'll be revisiting the APIs we provide, cleaning up the code, and adding docs. I'll keep this open until we've released some docs.

**Comment by ajacksified** [comment]
[we've released v3.0.0-rc.1](https://www.easypost.com/blog/2017-01-05-node-sdk-v3.html), which is fully documented.
