### ISSUE TITLE
Incorrect propType for shipment.usps_zone

### ISSUE THREAD

**Issue by justinwaite** [EasyPost/easypost-node#169]
Hey there,

It appears that the propType for `usps_zone` is incorrect. The API returns this as a `number`, but the propType is defined as a `string`.

https://github.com/EasyPost/easypost-node/blob/master/src/resources/shipment.js#L38

Screenshot of the response:
![image](https://user-images.githubusercontent.com/8517615/120738384-00fe8a80-c4ad-11eb-977d-3ce4d76e7b52.png)

This is breaking as I'm trying to update just the parcel dimensions on a shipment. My steps are:
1. Retrieve the shipment: `api.Shipment.retrieve(id)`
2. Mutate the parcel information `shipment.parcel.weight = 2`
3. Save the shipment: `shipment.save()`

This gives the error:
```
Invalid prop `usps_zone` of type `number` supplied to `Order`, expected `string`."
```

Maybe this isn't the right way to do it, so correct me if it's wrong.

**Comment by justinwaite** [comment]
For the record, I attempted to fetch and update individual parcels using the SDK, and was met with an error during the `save` operation:
```
{
  "error": {
    "error": {
      "code": "NOT_FOUND",
      "message": "The requested resource could not be found.",
      "errors": []
    }
  },
  "name": "RequestError"
}
```

Trying it out in postman, I don't think we're allowed to actually POST to the parcels/:id endpoint. Maybe this should be accounted for in the SDK?

**Comment by Justintime50** [comment]
Hey @justinwaite, thanks for writing in! EasyPost records are immutable (with a couple exceptions). Once a shipment is created, it cannot be updated. If you would like to update the parcel weight, you'll need to create a new shipment with updated parcel information. The `save` operation for a shipment is only meant to save a new record and not update an old one. A couple of notable exceptions of records that can be updated are things like a `carrier account` or `user details` but anything related to "shipping" (eg: parcels, addresses, shipments, etc) cannot be updated this way.

For additional info on the supported methods our client library provides, you can check out our API documentation on Node here: https://www.easypost.com/docs/api/node#shipments

As for the propType being wrong, it appears that we may have changed this from a string to an int under the hood some months back and need to update our documentation and propTypes here. Thanks for reporting this! I'll leave this open until I can confirm and then we can move forward with a PR if necessary to correct this.

**Comment by justinwaite** [comment]
Sweet, thanks! 

So is it okay to "orphan" these objects then? I don't need to run any sort of cleanup or deletion?

**Comment by Justintime50** [comment]
Exactly, we'll [eventually](https://support.easypost.com/hc/en-us/articles/360042847591-Data-Retention) purge them from our system, they are safe to leave behind as you continue creating new objects with the data you want.
