### ISSUE TITLE
easypost.js file is missing in the build

### ISSUE THREAD

**Issue by deepak-quo** [EasyPost/easypost-node#175]
```
0|main  | Error: Cannot find module './easypost.js'
0|main  | Require stack:
0|main  | - /home/ubuntu/node_modules/@easypost/api/index.js
```
Index.js file is importing easypost.js which is not present in the api directory.

**Comment by deepak-quo** [comment]
@Justintime50 I am using the latest one - v3.11.0

**Comment by Justintime50** [comment]
@deepak-quo thanks for reporting this! We've identified the issue in our build process and will correct this so it shouldn't happen again in the future. 

We are about to release 3.11.1 which should fix this issue.
