### ISSUE TITLE
API call for Shipment.prototype.getRates is POST instead of GET

### ISSUE THREAD

**Issue by andreipopovici** [EasyPost/easypost-node#18]
The code at https://github.com/EasyPost/easypost-node/blob/master/lib/main.js#L354 sends a POST request with undocumented parameters, but the docs at https://www.easypost.com/docs/api?lang=curl#shipping-rates suggest it should be a GET at shipments/:id/rates.

Am I understanding the docs or the code wrong, or is this a valid issue?

**Comment by att14** [comment]
There are actually 2 rates endpoints. One `/rates` and `/shipments/:id/rates`. The former is a POST and the later is a GET. Unfortunately this is inconsistent and they were mistaken for each other.

@victoryftw can you handle this?

**Comment by victoryftw** [comment]
This issue has been fixed in version 2.0.7
