### ISSUE TITLE
TypeScript declaration file (.d.ts)

### ISSUE THREAD

**Issue by yuyez** [EasyPost/easypost-node#184]
A d.ts [declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) would be quite helpful for TypeScript developers. Would it be possible for one to be included?

**Comment by Justintime50** [comment]
I believe this is being worked on as a part of #156

**Comment by oomphmade** [comment]
@Justintime50 any idea when this might get released?

**Comment by Justintime50** [comment]
As I'm not the one working on this I can't speak to when it would get released. It looks like the PR is still in draft mode and I'm unsure if the author is finished with it or not. I'd ping on the PR for more details from the author.

**Comment by oomphmade** [comment]
Thanks for your help I will ping directly on the PR

**Comment by Justintime50** [comment]
This has been merged to master and will be released in the next business week. For more details about Typescript support, please see the PR where it was added and the accompanying thread on #156.
