### ISSUE TITLE
Possible values form Shipment.status?

### ISSUE THREAD

**Issue by ruanmartinelli** [EasyPost/easypost-node#243]
Hey! Hope this is a good place for this kind of question.

I'm trying to figure out what are the possible values from the property `status` in the Shipments object. I've checked the PR with TypeScript definitions but it's only defined as `string` ([source](https://github.com/EasyPost/easypost-node/blob/b31143f8bfa7c5890a2470a173203073eb92b23b/types/Shipment/Shipment.d.ts#L122)). I also couldn't find in the official documentation.

Is there a place I can find all the possible values for this field?

Thanks!

**Comment by Justintime50** [comment]
The possible values of the `status` field can be viewed [here](https://www.easypost.com/docs/api#test-tracking-codes). They will be one of the possible EasyPost tracking statuses. If you have additional questions about our API, you can reach out to our support team at support@easypost.com.
