### ISSUE TITLE
[Feat]: Have the base `ErrorClass` extend Error

### ISSUE THREAD

**Issue by craigmichaelmartin** [EasyPost/easypost-node#257]
### Feature Request Is New

- [x] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

👋 Good afternoon! Thank you for all your work on this project!

I was wondering if there is a reason [ErrorClass](https://github.com/EasyPost/easypost-node/blob/dc0c7020157c72850866f249b8d080d33a2ce726/src/errors/error.js#L1) doesn't `extend Error` (and update the internals a bit).

My thought is that throwing custom errors which are instancesof `Error` is more expected, and works better with tooling in the community (eg, error monitoring tooling like [Sentry](https://sentry.io/welcome/) which expect instances of errors, and not objects).

I am only somewhat familiar with custom JavaScript error structures and its history with the introduction of custom error classes extending Error in ES2015, but would be happy to make a PR with these changes - if this is reasonable and desired.

Thanks again for EasyPost and all you do!

**Comment by nwithan8** [comment]
Thanks for the proposal!

Sounds like a good idea to me, especially if it will make our library interact nicer with other tools.

If you want to take a crack at a PR, that'd be great!

**Comment by Justintime50** [comment]
@craigmichaelmartin thanks for the suggestion! We plan to overhaul error handling in all our libs very shortly and are in the planning stages as we speak. We'll keep you posted when this is complete.

**Comment by nwithan8** [comment]
Hey @mwhearty , thanks for weighing in on this discussion and pointing this out.

We are right in the middle of a big rewrite of this library (part one in review here, feel free to comment: https://github.com/EasyPost/easypost-node/pull/345), which will include an overhaul of the `Error` class to fix some inconsistencies and oddities like this.

Be on the look out for a new major release of the Node library in the coming weeks!

**Comment by jchen293** [comment]
Hello everyone, we would like to express our gratitude once again for bringing this to our attention. We are pleased to inform you that this issue has been resolved in #349, where we have just completed an overhaul of our error handling. There are now two types of errors: `ApiError`, which is specific to errors from the API endpoint and it extends to `EasyPostError`, and `EasyPostError`, which is a general error from the library, such as when no lowest rate can be found. `EasyPostError` extends to the built-in Node `Error`.

We are expecting to release the `V6` overwrite within the next few weeks, so please stay tuned for that! I hope this information has been helpful to you. I am going to close this issue for now but please do not hesitate to let us know if you have any concerns, and thank you for choosing EasyPost 😄
