### ISSUE TITLE
question: is there are way to do multi-parcel shipments ?

### ISSUE THREAD

**Issue by gaboesquivel** [EasyPost/easypost-node#26]
on twitter they send me to php examples https://twitter.com/easypost/status/679346621176418304

example https://github.com/EasyPost/easypost-php/blob/master/examples/orders.php

on php, there's EasyPost::Order ... I can't find here or in the docs

**Comment by k-funk** [comment]
Currently that's not built in to the node library. We will do our best to implement that in a couple weeks.

**Comment by gaboesquivel** [comment]
cool thanks, let me if there's anything I can to do to help. I'm currently working on an app that needs guarantee multiple parcels are delivered together on the same date.

**Comment by eytanlevit** [comment]
+1

**Comment by gaboesquivel** [comment]
@k-funk any update on this?  
Currently the only the way to this would be using single parcel shipments with same label, right?

**Comment by k-funk** [comment]
What you're looking for is actually an endpoint called Orders. Not Batches. Batches is for buying multiple shipment labels in one call. We are in the process of writing Orders docs for our website, but unfortunately it's not built into the node library yet. We'll post here when it's available.

**Comment by gaboesquivel** [comment]
Thanks @k-funk.  So it seems that for the time being this is the process that will work for us:

- Create a batch of  5-10 shipments.
- Create a pickup for the batch.
- Use batch webhooks to track status.

We need to use [Fedex Call Tags](http://www.fedex.com/us/developer/product/WebServices/MyWebHelp_Oct08/Content/WS_Developer_Guide/Returns_Shipping.htm)  since our clients won't be printing labels. How can we do this through your API?

**Comment by gaboesquivel** [comment]
Hi we really need to clarify this about the Fedex printing the labels for the clients when creating a pickup.

**Comment by att14** [comment]
Hi @gaboesquivel, if you email us at support@easypost.com we will be much more responsive about inquiries unrelated to this library.

Currently, we do not support FedEx Call Tags. If you email us we can look into adding it to our backlog.

**Comment by gaboesquivel** [comment]
thanks, that's bad for us :/. Our mobile app users won't printing labels. You can close the issue now, or leave open for multi-parcel shipments.

**Comment by andrest** [comment]
@k-funk any updates on this?

**Comment by att14** [comment]
#28 implemented this feature.

**Comment by haseebsaif** [comment]
How to achieve this in NodeJS?

I am passing one parcel obj and I am getting the rates but when i try passed an array of parcel objs I am getting the error

**Comment by att14** [comment]
You can see the Node documentation for orders [here](https://www.easypost.com/docs/api/node#orders). If you are still receiving an error please reach out to support@easypost.com and they can help you.
