### ISSUE TITLE
Update Partner White Label Tests to Account for New `has_more` and `referral_customers` keys

### ISSUE THREAD

**Issue by Justintime50** [EasyPost/easypost-node#268]
# Summary

The responses to the retrieve All Referrals endpoint has been updated with two new attributes: 

  - The results of the list will now be wrapped in an attribute titled `referral_customers`
  - A "has_more" attribute (boolean) for pagination is now also included at the root level

## Acceptance Criteria

- [] Tests properly check the `referral_customers` key instead of the root list to ensure results are of type `User`
- [] Tests properly check that a `has_more` key is present and not set to `None`

**Comment by ryannguyen16** [comment]
i will look into this
