### ISSUE TITLE
[Bug]: `lowestRate()` returns rates for `USPS` even though requested only for `USPSReturns`

### ISSUE THREAD

**Issue by radmen** [EasyPost/easypost-node#323]
### Software Version

3.8.1, however the problem appears to be in the latest version too

### Language Version

Node v14.21.1

### Operating System

unrelated

### What happened?

1. Create new `Shipment`
2. Get lowest rate for `USPSReturns` (`shipment.lowestRate(['USPSReturns'])`)
3. Method returned the lowest rate but for the `USPS` carrier

### What was expected?

It should return the lowest rate for `USPSReturns` carrier.

### Sample Code

```node
const EasyPost = require('@easypost/api');

const client = new EasyPost(credentials);
const shipment = new client.Shipment(parcelData);
await shipment.save();

const lowestRate = shipment.lowestRate(['USPSReturns']);
```

**Comment by radmen** [comment]
I know we're using outdated version of the package, however the same issue is in the latest version:
https://github.com/EasyPost/easypost-node/blob/2fa71f90a76cfcfa40852019fffb8ee9513228fc/src/resources/util.js#L9-L16

The problem is that the helper tries to find a match using `contains()`. It iterates over the list of passed carriers (in our case [`USPSReturns`]), and checks if the `USPS` carrier is part of that name. It is, though it's not the same carrier we requested.

**Comment by radmen** [comment]
@Justintime50 dang, you're right. I'm not sure how I missed that... I'll reach out to our dev to get the details of the shipment that supposedly failed.

Thank you!

**Comment by radmen** [comment]
@Justintime50 turns out... it was all over a deployment issue. I'm sorry for taking your time. There's nothing to be resolved. Thank you!

**Comment by Justintime50** [comment]
Glad you were able to figure it out!
