### ISSUE TITLE
Odd API Response

### ISSUE THREAD

**Issue by kennetpostigo** [EasyPost/easypost-node#33]
I'm currently testing out the `easypost-node` using the code from `example.js` in the repo with my test `apiKey`. However I would get a response that says the following:
```js
{ message:
   { code: 'BAD_REQUEST',
     message: 'Invalid parameters were passed and the record could not be persisted.',
     errors: [ [Object] ] },
  param: undefined }
```

Following this message I receive the log of the shipment from `console.log(shipment)` statement in the `easypost.Shipment.create({...})` call which has the shipment information. I know that the call succeeds because it appears in the test shipments on my 'manage shipments' page on the easypost website.

Im wondering why the BAD_REQUEST` response is happening.

**Comment by sandysaders** [comment]
I've come across this same issue and not sure what is going wrong.

**Comment by att14** [comment]
If you write into support@easypost.com I can provide you with more information. I'm going to close this for now, but if we determine it is a client library issue I will reopen.

**Comment by cantonyselim** [comment]
I'm having this exact same problemsIt really defeats the point of GitHub issues if the threads always end with "write into support@easypost.com". Looking at this thread now it's really no help to figure out whats going wrong with my app. It may as well have not been posted here and just been an email exchange with EasyPost Support.

**Comment by att14** [comment]
These request can contain PII or other sensitive information so we would prefer not to use GitHub for non-client related issues.
