### ISSUE TITLE
Installed module is too large due to types/demo/node_modules in .tgz file

### ISSUE THREAD

**Issue by mwhearty** [EasyPost/easypost-node#343]
Perhaps a mistake was made when publishing the .tgz file for version 5.10.0?

Installing the module includes all of the types/demo/node_modules because those are contained in the .tgz file. 

This adds 70 MB to this module's footprint, problem for us as we use the module in an AWS lambda function.

**Comment by Justintime50** [comment]
Thanks for reporting this! I apologize for the bloated size of the package, the inclusion of the subdirectory `node_modules` was never intended. We’ll work on putting up a patch for this shortly that excludes the additional `node_modules` and let you know when this gets released.

**Comment by Justintime50** [comment]
Thanks again for reporting this @mwhearty! We have released `v5.10.1` which corrects the files get packaged in the final release. Thanks to your report, we were able to tighten up our releasing process for this library and bring the final package size from the normal 2.5mb to ~500kb unpacked.

We apologize for the inconvenience and hope the new version works for your needs. Please let us know if there's anything else related to this we can help with.

v5.10.0 (bloated):
![Screen Shot 2023-02-06 at 11 08 50 AM](https://user-images.githubusercontent.com/39606064/217052243-924cdb18-a546-48e6-8dd2-2a170eeb2b72.png)

v5.10.1 (corrected):
![Screen Shot 2023-02-06 at 11 08 38 AM](https://user-images.githubusercontent.com/39606064/217052267-c93a0a49-cfba-4405-b980-205947824246.png)
