### ISSUE TITLE
EasyPost IRC/Slack/Gitter

### ISSUE THREAD

**Issue by sandysaders** [EasyPost/easypost-node#35]
Hello,

I wanted to know if there was an easy post IRC/Slack/GItter that developers can use to talk with people who know `easypost` API well. Similar to how `stripe` payment company has an IRC for developers to talk to the stripe engineers about their API. If there isn't would EasyPost be willing to create an IRC or Slack or Gitter?

**Comment by att14** [comment]
No we don't have a messaging client, but our support is handled by engineers. So feel free to write to support@easypost.com any time and we will provide assistance.
