### ISSUE TITLE
create carrier Account

### ISSUE THREAD

**Issue by urielcastrillon08** [EasyPost/easypost-node#36]
Hello
is possible create CarrierAccount whit this wrap?

**Comment by ajacksified** [comment]
Not currently, although it is likely to come in the near future.

**Comment by ajacksified** [comment]
@urielcastrillon08 - [we've released v3.0.0-rc.1](https://www.easypost.com/blog/2017-01-05-node-sdk-v3.html). It is up on NPM as 3.0.0-rc.1, and tagged here as well. You will be able to create CarrierAccounts with this update.
