### ISSUE TITLE
Link to docs from github page leads to 404

### ISSUE THREAD

**Issue by mikejohanson** [EasyPost/easypost-node#367]
![image](https://user-images.githubusercontent.com/9046277/232270939-ed2b5816-8281-428a-a39c-175a83b6a830.png)

![image](https://user-images.githubusercontent.com/9046277/232271073-9b63b652-64d0-4a7b-8bec-3bd870ad3708.png)

**Comment by Justintime50** [comment]
Thanks for reporting this! We've corrected the link.
