### ISSUE TITLE
[Bug]: Type definition of `Shipment.lowestRate` function should not be static

### ISSUE THREAD

**Issue by mattcroissant** [EasyPost/easypost-node#395]
### Software Version

6.6.1

### Language Version

v16.15.1

### Operating System

MacOS Ventura 13.3.1 (a)

### What happened?

The Typescript type definition of `Shipment.lowestRate` defines the function as being static: https://github.com/EasyPost/easypost-node/blob/master/types/Shipment/Shipment.d.ts#L285

In reality, the `Shipment.lowestRate` is not a static function: https://github.com/EasyPost/easypost-node/blob/2c07ac2c727dcffe23eef1543b39fe68a2a65afa/src/models/shipment.js#L44

### What was expected?

The expectation would be that the Typescript type definition defines the `Shipment.lowestRate` function as not being static.

**Comment by nwithan8** [comment]
Thank you for reporting this. We are re-checking our TypeScript definitions as, with the recent [thread-safe rewrite](https://github.com/EasyPost/easypost-node/releases/tag/v6.0.0), the majority of our functions are no longer static.
