### ISSUE TITLE
Hi, after I install node-easypost using npm install node-easypost --save, I build and run. I have an error: can not find module ./easypost.js. I find that line is in index.js row 1, how can I generate easypost.js file?

### ISSUE THREAD

**Issue by hosiduy** [EasyPost/easypost-node#41]

**Comment by maiab** [comment]
Hey @hosiduy I had the same problem. 

Instead of using 3.0, I installed version 2.1.1.

Then I needed to append 

`node: {fs: "empty"}`

to my webpack config.

See https://github.com/josephsavona/valuable/issues/9

**Comment by ajacksified** [comment]
@maiab and @hosiduy - 3.0 should be good to import now.

As this is a RC, any feedback you have about breakages would be extremely helpful!

**Comment by ajacksified** [comment]
1de8c2d393f2dcaa153c8ae69fc602ad7b1027d0
