### ISSUE TITLE
`tracker` Nullable on `IShipment`

### ISSUE THREAD

**Issue by torickjdavis** [EasyPost/easypost-node#418]
After purchasing a Shipment through `client.Shipment.buy`, the resulting object's `tracker` property was `null`. The [example from the documentation](https://www.easypost.com/docs/api/node#create-a-shipment) also shows the resulting `tracker` to be `null`, which contradicts the types defined for the `IShipment` assure that it exists.

https://github.com/EasyPost/easypost-node/blob/891e4a50897b64e8ead923ad894d1b92ff388861/types/Shipment/Shipment.d.ts#L125

```ts
tracker: ITracker | null;
```

I would open a PR with my suggestion above; however, there could possibly be several other properties that might have a similar issue that may need to be reviewed based on actual business logic, and could then be released together.

**Comment by nwithan8** [comment]
Hello, thanks for reaching out! Can you provide us with a bit more information, perhaps a code snippet to help us recreate the issue?

From what we've been able to diagnose so far:

- A "tracker" object is supposed to be included as part of the response for a "buy a shipment" API call. (Your link goes to the "create a shipment" API call; the buy one is [here](https://www.easypost.com/docs/api/node#buy-a-shipment), which does have a populated "tracker" in the response body.)

- Looking at our unit test cassettes, "tracker" is populated in the [recorded HTTP response](https://github.com/EasyPost/easypost-node/blob/891e4a50897b64e8ead923ad894d1b92ff388861/test/cassettes/Shipment-Service_2987889512/buys-a-shipment_3413405727/recording.har#L213C21-L214C1) to "buy a shipment", and is confirmed to be deserialized properly by the following unit test:
<img width="845" alt="image" src="https://github.com/EasyPost/easypost-node/assets/17054780/6a52adf1-1935-4ddf-8872-31c9a5747983">


We're not aware of any changes to the API that would affect this, and live tests to the API appear to be working as expected, so we can't immediately identify any issue with the library itself. If you could provide us with an example of your workflow, so we can rule out any potential user error. After that, we may need to direct you to our customer support team to diagnose a potential issue specifically with your individual shipment.

Looking forward to hearing from you!

**Comment by nwithan8** [comment]
Hello, thanks for reaching out with the suggestion! We are in the process of improving and embracing TypeScript definitions, as will take this under consideration!

We've noted this in our internal workboard, so I'm going to close this ticket for now. We'll update it when an associated PR has been released!

**Comment by torickjdavis** [comment]
@nwithan8, thanks for such a quick response! I look forward to future updates!
