### ISSUE TITLE
Header error on creating shipment

### ISSUE THREAD

**Issue by katherinebui** [EasyPost/easypost-node#42]
<img width="582" alt="screen shot 2017-01-18 at 3 03 39 pm" src="https://cloud.githubusercontent.com/assets/15624292/22086794/5e296e46-dd8f-11e6-89d4-a32bae3601d9.png">

I am using the example code from the ReadMe. Every time I try to save the shipment information, I get this error.

**Comment by ajacksified** [comment]
v3.0.0-rc.4 fixes the unsafe header errors; however, we don't allow CORS on our APIs. You will need to build an API proxy which holds the API keys, and make your requests through that proxy.
