### ISSUE TITLE
[Feat]: Add Refund to EasyPost.d.ts

### ISSUE THREAD

**Issue by akawalsky** [EasyPost/easypost-node#433]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

Right now there is no typesafe way to communicate with `Refunds` routes via the typescript sdk.

**Comment by Justintime50** [comment]
Thanks for reporting this! Looks like we are missing a couple actually. We'll get a fix out for this soon.
