### ISSUE TITLE
[Bug]: CustomsItem value type doesn't match documented type

### ISSUE THREAD

**Issue by thattyson** [EasyPost/easypost-node#447]
### Software Version

7.2.0

### Language Version

20.9.0

### Operating System

macOS 14.1.2

### What happened?

1. Attempt to add a CustomsItem to CustomsInformation
2. Build the CustomsItem with all required properties.
3. Receive an error that the expected type is `float` for `value`, rather than a `string` as is [documented](https://www.easypost.com/docs/api#customs-items).

### What was expected?

The package type for `value` should match the documented type in the API docs.

I would also suggest documenting `value` more clearly, telling the user if the value should be in dollars or cents. As is, it's unclear unless looking at the example JSON. For other dollar values the documentation shows "USD formatted dollars and cents, delimited by a decimal point". This would clarify.

**Documentation**
<img width="720" alt="API documentation" src="https://github.com/EasyPost/easypost-node/assets/1786938/c71f2e82-bb47-4fb7-88d2-9c82b7ca8ff3">

**Package**
```
  /**
   * Required, greater than zero, total value (unit value * quantity)
   * float (USD)
   */
  value: number;
```

**Comment by Justintime50** [comment]
Hey @thattyson, thanks for submitting this!

The Typescript definition in this case is correct. Additionally, the screenshot you shared is of our old docs. You will want to [view our new docs](https://docs.easypost.com/docs/customs-items) which we just released this last week which have the type corrected along with the clarification to use USD. The old docs will be taken offline in the next couple months and should be considered deprecated. Hope this helps!
