### ISSUE TITLE
[Bug]: HMAC encryption mismatch 

### ISSUE THREAD

**Issue by footcarts** [EasyPost/easypost-node#467]
### Software Version

7.5.0

### Language Version

Nodejs

### Operating System

Mac OS

### What happened?

The weight field in the tracker.updated EasyPost webhook is not properly formatted as JSON. When included, it appears as "weight": 136.0. However, when parsed as JSON, it is always reformatted to "weight": 136. This discrepancy leads to a mismatch of hashes when using the validateWebhook function.

As a result, about 50% of our webhooks are failing because some include a value for weight, while others have a value of null. When the weight field has a value of null, there is no issue with verifying the hash.

To work around this problem, we are using regex to insert the decimal point:

```
validateWebhook(
      Buffer.from(
        JSON.stringify(req.body).replace(/("weight":)(\d+)(?!\.\d)/g, "$1$2.0")
      ),
      headers["x-hmac-signature"],
      "12345"
    );
```
      
   

### What was expected?

Expected properly formatted JSON to be encrypted with the secret

**Comment by Justintime50** [comment]
Can confirm, recreated:

```js
JSON.parse(Buffer.from(JSON.stringify({"weight": 136.0})).toString())
{ weight: 136 }
```

We'll take a look and see about a fix, thanks for reporting this!

**Comment by Justintime50** [comment]
@footcarts mind sharing what kind of eventBody you are getting for this that's causing troubles? I want to take a look at what kinds of fields/data may be coming through that could also cause this.
