### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by bryton** [EasyPost/easypost-node#54]
TypeError: fromAddress.save is not a function

Any ideas?

**Comment by ajacksified** [comment]
What version of the SDK do you have installed?

**Comment by bryton** [comment]
2.1.1

**Comment by k-funk** [comment]
The basic example you're referring to is the README on v3.x.x. If you want to continue using 2.1.1, see that README: https://github.com/EasyPost/easypost-node/tree/v2.1.1

**Comment by bryton** [comment]
It seems like the npm default published version was 2.1.1 - I upgraded to 3.0.0-rc.14 and it worked. Thanks!
