### ISSUE TITLE
Buy API: UnhandledPromiseRejectionWarning and DeprecationWarning in Node

### ISSUE THREAD

**Issue by tonydiaz** [EasyPost/easypost-node#55]
I'm running in to an error when trying to walk through the "Getting Started" document: https://www.easypost.com/getting-started/node.html#step4

Specifically it seems everything works except the **Buy Shipment** example

This is the error I'm seeing when the `buy` API is being called:
```
(node:31575) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): [object Object]
(node:31575) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have tried to call the `buy` API two ways the first from the Getting Started example the second from the API docs. Both return the same warning and are never successfully called.  
Here is the snippet of code I'm using from the document:

```javascript
  async.waterfall([
    function(callback) {
      const shipment = new api.Shipment({
            to_address: new api.Address({
              name: 'George Costanza',
              company: 'Vandelay Industries',
              street1: '1 E 161st St.',
              city: 'Bronx',
              state: 'NY',
              zip: '10451'
            }),
            from_address: new api.Address({
              company: 'EasyPost',
              street1: '417 Montgomery Street',
              street2: '5th Floor',
              city: 'San Francisco',
              state: 'CA',
              zip: '94104',
              phone: '415-528-7555'
            }),
            parcel: new api.Parcel({
              predefined_package: 'Card',
              weight: 1,
            })
        })
        callback(null, shipment);
    },
    function(shipment, callback) {
        shipment.save().then(console.log)
        callback(null, shipment);
    },
    function(shipment, callback) {
        shipment.buy(shipment.lowestRate(['USPS'], ['First']))
        .then(console.log)
        callback(null, 'done');
    }
  ], function (err, result) {
  });
```
The second way I tried to call the API using the Shipment ID I recieved in place of `shp..`
```javascript
  api.Shipment.retrieve('shp_..').then(s => {
  s.buy(s.lowestRate(), 0).then(console.log);
  });
```

I'm using Node version 7.5.0 and npm version 4.1.2.

Any help would be appreciated.

**Comment by k-funk** [comment]
Just ran your code locally and it worked for me.

Make sure the top of your file looks like: 

    const apiKey = '<your_secret_test_api_key>';
    const EasyPost = require('node-easypost');
    const async = require('async');

    const api = new EasyPost(apiKey);

If you're still having the problem, let us know what version of node-easypost you're using. I tested with `3.0.0-rc.14`.

**Comment by ajacksified** [comment]
Your code doesn't look properly asynchronous. You're calling `callback` immediately, instead of when the promise completes; you have:

```
function(shipment, callback) {
        shipment.save().then(console.log)
        callback(null, shipment);
    },
    function(shipment, callback) {
        shipment.buy(shipment.lowestRate(['USPS'], ['First']))
        .then(console.log)
        callback(null, 'done');
    }
```

when you should be using:

```
function(shipment, callback) {
  shipment.save().then((s) => { console.log(s); callback(null, shipment) });
},
function(shipment, callback) {
  shipment.buy(shipment.lowestRate(['USPS'], ['First'])).then((s) => {
    console.log(s);
    callback(null, 'done')
  });
}
```
The error is likely that you're trying to buy before the shipment is saved. You can also capture the errors as a second param to the `then`:

```
function(shipment, callback) {
  shipment.save().then((s) => {
    console.log(s);
    callback(null, shipment);
  }, (err) => { callback(err) });
},
function(shipment, callback) {
  shipment.buy(shipment.lowestRate(['USPS'], ['First'])).then((s) => {
    console.log(s); 
    callback(null, 'done');
  }, (err) => { callback(err); });
}
```

You should be able to globally capture unhandled exceptions using code like the following:

```
process.on('unhandledRejection', (err) => {
    console.log(err);
});
```

**Comment by tonydiaz** [comment]
Thanks @k-funk and @ajacksified It was an issue with my code not properly doing the callbacks as @ajacksified suggested. I'm able to generate a test label now. Thanks for the help!
