### ISSUE TITLE
Error creating new Tracker on Meteor server

### ISSUE THREAD

**Issue by jalavosus** [EasyPost/easypost-node#56]
Version: 3.0.0-rc.14

Platform: macOS 10.11.something

Usage: Meteor/React

In my Meteor /server/main.js, I have the following code:

```
import { Meteor } from 'meteor/meteor';
import EasyPost from "node-easypost";
var epAPI = new EasyPost(/*omitted*/);

Meteor.startup(() => {
  Meteor.methods({
     createTracker: function (tracking_code, carrier=None) {
        if (carrier) {
           return new epAPI.Tracker({tracking_code: tracking_code, carrier: carrier}).save();
        }
        return new epAPI.Tracker({tracking_code: tracking_code}).save();
     }
 });
});
```

And it gets called by the client like so (though, in Coffeescript): 

```
usps_ex: Meteor.call 'createTracker',
         "EZ064612938US",
         "USPS"
```

When this runs (as it's supposed to on page load), Meteor produces the following error in the console:

```
I20170312-14:29:02.039(-4)? Exception while invoking method 'createTracker' [object Object]
I20170312-14:29:02.040(-4)?     at e.<anonymous> (/Users/james/Workspace/exo/node_modules/node-easypost/easypost.js:2:20361)
I20170312-14:29:02.040(-4)?     at tryCatch (/Users/james/Workspace/exo/node_modules/regenerator-runtime/runtime.js:64:40)
I20170312-14:29:02.041(-4)?     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/james/Workspace/exo/node_modules/regenerator-runtime/runtime.js:299:22)
I20170312-14:29:02.041(-4)?     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/james/Workspace/exo/node_modules/regenerator-runtime/runtime.js:116:21)
I20170312-14:29:02.041(-4)?     at n (/Users/james/Workspace/exo/node_modules/node-easypost/easypost.js:2:16966)
I20170312-14:29:02.042(-4)?     at /Users/james/Workspace/exo/node_modules/node-easypost/easypost.js:2:17091
I20170312-14:29:02.042(-4)?     at /Users/james/.meteor/packages/promise/.0.8.8.bjauo3++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:32:39
```

I feel like I'm doing something wrong here, I'm just not sure what it is.

Thanks in advance!

**Comment by k-funk** [comment]
This is happening because you've created an invalid Tracker, and you are not handling the error.

I'm assuming that you created this Tracker with your Test API Key. All Trackers created in test need to use a provided `tracking_code` such as `'EZ4000000004'`. [See the EasyPost Documentation](https://www.easypost.com/docs/api#testing-specific-tracking-states) for the full list of codes.

You can see the error for yourself by running this:

    const EasyPost = require('node-easypost');
    const epAPI = new EasyPost('<test_api_key>');

    const trackingCode = 'EZ064612938US';
    const carrier = 'USPS';
    const tracker = new epAPI.Tracker({tracking_code: trackingCode, carrier: carrier}).save();
    tracker.then(console.log, console.error);
