### ISSUE TITLE
Label - unable to generate in PDF

### ISSUE THREAD

**Issue by bryton** [EasyPost/easypost-node#57]
Hello all, I tried to generate a PDF label, I tried two things:

1) Setting label_format: 'PDF' when creating a shipment
2) Trying shipment.convertLabelFormat('PDF'), to which I got the error:
console.log(err.message)
< Status undefined returned from API request to shipments/shp_8e51e7a752064ecdbef7cdf003614cbf/label
The requested resource could not be found.

Any idea how to generate a label in PDF? It's only generating in PNG for me. Thanks!

**Comment by ajacksified** [comment]
@bryton should be fixed with 3.0.0-rc.15, if you could give it a shot.

**Comment by bryton** [comment]
It was fixed, thanks!
