### ISSUE TITLE
Customs created_at and updated_at date fail validation on 3.0.0-rc.16

### ISSUE THREAD

**Issue by brianpowell** [EasyPost/easypost-node#60]
<img width="867" alt="screen shot 2017-03-20 at 8 24 14 pm" src="https://cloud.githubusercontent.com/assets/2650513/24127570/fb66c4fa-0dab-11e7-9383-3dc603516215.png">

**Comment by k-funk** [comment]
It appears as though you're creating a CustomsInfo with `object`,`created_at`, `updated_at` as empty strings. These fields are auto-generated by EasyPost, so they don't need to be passed. See https://www.easypost.com/docs/api/node.html#customs-infos-create-codesample
