### ISSUE TITLE
batch.buy() is not a function

### ISSUE THREAD

**Issue by gregkop** [EasyPost/easypost-node#65]
I'm having an issue purchasing batch labels, once I've created a batch, waited until it's been created and retrieved it - I cannot call the .buy() function. I'm currently using version 3.0.0-rc.21 of the library. Any ideas what I can do?

**Comment by ajacksified** [comment]
The node client library doesn't currently implement `buy` on batch - it only covers documented APIs. In the meantime, you can iterate through the shipment ids, pull those and run `buy` on each shipment. I will keep this issue open until implemented (it should be soon.)
