### ISSUE TITLE
Question: Create a Shipment from Address IDs in Node.js

### ISSUE THREAD

**Issue by tonydiaz** [EasyPost/easypost-node#70]
Is it possible to create a shipment using address IDs in Node.js? I see the example on how to do it with a Curl command but no example for Node.js

The docs seems to state it needs an address object: https://www.easypost.com/docs/api.html#shipments

**Comment by k-funk** [comment]
Yep, that works:

```
const parcel = new api.Parcel({
  length: 20.2,
  width: 10.9,
  height: 5,
  weight: 65.9
});

const shp1 = new api.Shipment({
    to_address: 'adr_...',
    from_address: 'adr_...',
    parcel: parcel
});

shp1.save().then(console.log)
```
