### ISSUE TITLE
Setting batch in api.Pickup doesn't work

### ISSUE THREAD

**Issue by barbatus** [EasyPost/easypost-node#71]
I am getting error `PICKUP.REQUEST.INVALIDInvalid request, a batch with shipments or a shipment is required to create a Pickup.` while I provide valid shipping batch (with valid shipments) which has `label_generated` status. Also I noticed that `api.Pickup` is missing `batch` param in `propTypes` while `shipment` is there. Can you please clarify whether it's an issue or I am missing something. Thanks!

**Comment by ajacksified** [comment]
Shipped as v3.0.7. Thanks for the report!

**Comment by barbatus** [comment]
@ajacksified Can you please add `reference` to the `api.Shipment`, we need it to have an order ID shown in the shipment label.

**Comment by k-funk** [comment]
@barbatus done.
