### ISSUE TITLE
delete() not a function for CarrierAccount

### ISSUE THREAD

**Issue by mikejohanson** [EasyPost/easypost-node#90]
I'm trying to follow the sample code here:
```
const Easypost = require('@easypost/api');
const api = new Easypost('<YOUR_PRODUCTION_API_KEY>');

api.CarrierAccount.retrieve('ca_...').then(ca => ca.delete());

// or

const ca = new api.CarrierAccount({ id: '<ca_...>' });
ca.delete();
```
However, both of those ways result in: `ca.delete is not a function`. Has this been implemented in this library?

**Comment by k-funk** [comment]
Looks like our docs at https://www.easypost.com/docs/api/node.html#delete-a-carrier-account are currently wrong.

You can delete a Carrier Account using the static method:
`api.CarrierAccount.delete('ca_...').then(console.log)`

Thanks for bringing this to our attention. We will either update our docs, or allow `.delete()` on instances.

**Comment by ajacksified** [comment]
Deploying as 3.1.1.
